[platformio]
default_envs = ble

[env:xiao_esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.31/platform-espressif32.zip
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
build_flags = -Wall -Wextra

build_src_filter = +<main.cpp>

[env:ble]
extends = env:xiao_esp32s3
build_src_filter = +<ble.cpp>
lib_deps = h2zero/NimBLE-Arduino@2.5.0
